name: Publish Site to Interwebs

on:
  push:
    branches: [ main ]
jobs:
  schemas-deploy:
    name: Publish
    runs-on: ubuntu-latest  
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Upload images to site
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./assets
